OUT_DIR_REL: runs/Section4_3_SBNN-VL/output
FIG_DIR_REL: runs/Section4_3_SBNN-VL/figures
EMBEDDING_LAYER: True
BASIS_LENGTH_SCALE: 1
SQRT_EMBEDDING_SIZE: 15
PRIOR_PER: 'layer'
DO_STAGE2: False
KERNEL_CLASS: base.Isotropic
KERNEL_FUNCTION: 'Matern32'
KERNEL_LENGTH_SCALE: 1.5
KERNEL_AMPLITUDE: 0.2
LOGNORMAL: True
SPATIALLY_VARYING_PARAMETERS: True
OUTER_LOOP_ITERS: 20000
OUTER_LOOP_LR: 0.001
N_SIM_BATCH: 512
THIN: None