OUT_DIR_REL: runs/Section4_1_BNN-IL/output
FIG_DIR_REL: runs/Section4_1_BNN-IL/figures
EMBEDDING_LAYER: False
SQRT_EMBEDDING_SIZE: None
PRIOR_PER: 'layer'
DO_STAGE2: False
KERNEL_CLASS: base.Isotropic
KERNEL_FUNCTION: 'RBF'
KERNEL_LENGTH_SCALE: 1.0
KERNEL_AMPLITUDE: 1.0
LOGNORMAL: False
SPATIALLY_VARYING_PARAMETERS: False
OUTER_LOOP_ITERS: 4000
OUTER_LOOP_LR: 0.003
N_SIM_BATCH: 1024
THIN: None