OUT_DIR_REL: runs/Section4_3_SBNN-IL/output
FIG_DIR_REL: runs/Section4_3_SBNN-IL/figures
EMBEDDING_LAYER: True
BASIS_LENGTH_SCALE: 1
SQRT_EMBEDDING_SIZE: 15
PRIOR_PER: 'layer' # could be 'parameter'
DO_STAGE2: False
KERNEL_CLASS: base.Isotropic
KERNEL_FUNCTION: 'Matern32'
KERNEL_LENGTH_SCALE: 1.5
KERNEL_AMPLITUDE: 0.2
LOGNORMAL: True
SPATIALLY_VARYING_PARAMETERS: False
OUTER_LOOP_ITERS: 20000
OUTER_LOOP_LR: 0.003
N_SIM_BATCH: 1024
THIN: None