OUT_DIR_REL: runs/Section4_2_SBNN-IP/output
FIG_DIR_REL: runs/Section4_2_SBNN-IP/figures
EMBEDDING_LAYER: True
BASIS_LENGTH_SCALE: 1
SQRT_EMBEDDING_SIZE: 15
PRIOR_PER: 'parameter'
DO_STAGE2: False
KERNEL_CLASS: base.Nonstationary
KERNEL_FUNCTION: 'RBF'
KERNEL_LENGTH_SCALE: 1.0
KERNEL_AMPLITUDE: 1.0
LOGNORMAL: False
SPATIALLY_VARYING_PARAMETERS: False
OUTER_LOOP_ITERS: 4000
OUTER_LOOP_LR: 0.003
N_SIM_BATCH: 1024
THIN: None