OUT_DIR_REL: runs/Section5_2_SBNN-IP/output
FIG_DIR_REL: runs/Section5_2_SBNN-IP/figures
DATA_FILE_REL: intermediates/max_stable_data_Gumbel.npy
EMBEDDING_LAYER: True
N_LAYERS: 3
BASIS_LENGTH_SCALE: 1
SQRT_EMBEDDING_SIZE: 20
PRIOR_PER: 'parameter'
DO_STAGE2: True
N_OBS: [50, 100, 1000, 5000]
LOGNORMAL: False
SPATIALLY_VARYING_PARAMETERS: False
OUTER_LOOP_ITERS: 10000
OUTER_LOOP_LR: 0.003
N_SIM_BATCH: 512
RE_TRAIN: True
THIN: 1000
N_PLOT: 200
BIG_PRIOR_SAMPLE: 10000